### ISSUE TITLE
config.toml remove doks theme residue

### ISSUE THREAD

**Issue by cpswan** [atsign-foundation/atsign.dev#63]
**Describe the bug**
[config.toml](https://github.com/atsign-foundation/atsign.dev/blob/trunk/config.toml) presently has this at the bottom, which is likely to cause trouble at some stage:

```toml
# Doks theme experiment
baseurl = "/"
canonifyURLs = false
disableAliases = true
disableHugoGeneratorInject = true
enableEmoji = true
enableGitInfo = false
enableRobotsTXT = true
languageCode = "en-US"
paginate = 7
rssLimit = 10
```
